routes/admin.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Route::middleware('auth')->group(function() {
    Route::prefix('admin')->group(function () {
        Route::resources([
            'products' => App\Http\Controllers\Backoffice\ProductController::class,
        ]);
    });

    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

});

require __DIR__.'/auth.php';

routes/web.php
<?php

use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [TestController::class, 'portofolio']);
Route::get('/home', [TestController::class, 'portofolio']);
// Route::get('/portofolio', function () {
//     return view('portofolio');
// });

Route::get('/shop',[TestController::class, 'shop']);

app/Http/Controllers/Backoffice/ProductController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Product::latest();

            return DataTables::eloquent($data)
            ->addIndexColumn()
            ->addColumn('action', function ($data) {
                $btn =
                "<td>
                    <button id='btn-edit' type='button' class='btn btn-sm icon btn-success' data-bs-toggle='modal' data-bs-target='#form-modal'  onclick='editData({$data->id})'><i class='bi bi-pencil'></i></button>
                    <button id='btn-delete' type='button' class='btn btn-sm icon btn-danger' data-bs-toggle='modal' data-bs-target='#form-modal' onclick='deleteData({$data->id})'><i class='bi bi-trash'></i></button>
                </td>";
                return $btn;
            })
            ->rawColumns(['action'])
            ->toJson();
        }
        return view('backoffice.barang.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $table = Product::create($request->all());
        return response()->json(['message' => 'Data Added successfully.', 'data' => $table]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $table = Product::find($id);
        return response()->json(['data' => $table]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $table = Product::find($id);
        return response()->json(['data' => $table]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $table = Product::find($id)->update($request->all());
        return response()->json(['message' => 'Data Updated successfully.', 'data' => $table]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Product::find($id)->delete();
        return response()->json(['message' => 'Data Deleted successfully.']);
    }
}

resources/views/backoffice/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Backoffice - @yield('title')</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter">

    <link rel="stylesheet" href="{{ url('assets/css/main/app.css') }}">
    <link rel="stylesheet" href="{{ url('assets/css/main/app-dark.css') }}">
    <link rel="stylesheet" href="{{ url('assets/images/logo/favicon.svg') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url('assets/images/logo/favicon.png') }}" type="image/png">
    <link rel="stylesheet" href="{{ url('assets/css/shared/iconly.css') }}">
    <link rel="stylesheet" href="{{ url('assets/extensions/filepond/filepond.css') }}">
    <link rel="stylesheet" href="{{ url('assets/extensions/filepond-plugin-image-preview/filepond-plugin-image-preview.css') }}">
    <link rel="stylesheet" href="{{ url('assets/extensions/toastify-js/src/toastify.css') }}">
    <link rel="stylesheet" href="{{ url('assets/css/pages/filepond.css') }}">

    @vite(['resources/js/app.js'])

    @yield('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="{{ url('assets/custom.css') }}">
</head>

<body>
    <div id="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active">
                <div class="sidebar-header position-relative">
                    @include('backoffice.layouts.sidebar-header')
                </div>
                <div class="sidebar-menu">
                    @include('backoffice.layouts.sidebar-menu')
                </div>
            </div>
        </div>
        <div id="main">
            <header class='mb-3'>
                <nav class="navbar navbar-expand navbar-light navbar-top">
                    <div class="container-fluid">
                        <a href="#" class="burger-btn d-block">
                            <i class="bi bi-justify fs-3"></i>
                        </a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mb-lg-0">
                            </ul>
                            <div class="dropdown">
                                <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                    <div class="user-menu d-flex">
                                        <div class="user-name text-end me-3">
                                            <h6 class="mb-0 text-gray-600">{{ Auth::user()->name }}</h6>
                                            <p class="mb-0 text-sm text-gray-600">{{ Auth::user()->email }}</p>
                                        </div>
                                        <div class="user-img d-flex align-items-center">
                                            <div class="avatar avatar-md">
                                                <img src="{{ url('assets/images/faces/1.jpg') }}">
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton" style="min-width: 11rem;">
                                    <li>
                                        <h6 class="dropdown-header">Hello, {{ Auth::user()->name }}!</h6>
                                    </li>
                                    <li><a class="dropdown-item" href="{{ route('profile.edit') }}"><i class="icon-mid bi bi-person me-2"></i> My
                                            Profile</a></li>
                                    <form action="{{ route('logout') }}" method="POST">
                                        @csrf
                                        <li><button type="submit" class="dropdown-item"><i
                                            class="icon-mid bi bi-box-arrow-left me-2"></i> Logout</button></li>
                                    </form>
                                </ul>
                            </div>
                        </div>
                    </div>
                </nav>
            </header>

            <div class="page-heading">
                @yield('page-heading')
            </div>
            <div class="page-content">
                @yield('content')
            </div>

            <footer>
                <div class="footer clearfix mb-0 text-muted">
                    <div class="float-start">
                        <p>2023 &copy; </p>
                    </div>
                    <div class="float-end">
                        <p>Template by <a href="https://zuramai.github.io/mazer/">Mazer</a></p>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <script src="{{ url('assets/js/bootstrap.js') }}"></script>
    <script src="{{ url('assets/js/app.js') }}"></script>
    <script src="{{ url('assets/extensions/filepond/filepond.js') }}"></script>
    <script src="{{ url('assets/extensions/toastify-js/src/toastify.js') }}"></script>
    <script src="{{ url('assets/js/pages/filepond.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>

    @yield('script')

</body>

</html>

resources/views/backoffice/layouts/sidebar-header.blade.php
<div class="d-flex justify-content-between align-items-center">
    <div class="logo">
        <a href="index.html"><img src="{{ url('assets/images/logo/logo.svg') }}" alt="Logo" srcset=""></a>
    </div>
    <div class="theme-toggle d-flex gap-2  align-items-center mt-2">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--system-uicons" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 21 21"><g fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M10.5 14.5c2.219 0 4-1.763 4-3.982a4.003 4.003 0 0 0-4-4.018c-2.219 0-4 1.781-4 4c0 2.219 1.781 4 4 4zM4.136 4.136L5.55 5.55m9.9 9.9l1.414 1.414M1.5 10.5h2m14 0h2M4.135 16.863L5.55 15.45m9.899-9.9l1.414-1.415M10.5 19.5v-2m0-14v-2" opacity=".3"></path><g transform="translate(-210 -1)"><path d="M220.5 2.5v2m6.5.5l-1.5 1.5"></path><circle cx="220.5" cy="11.5" r="4"></circle><path d="m214 5l1.5 1.5m5 14v-2m6.5-.5l-1.5-1.5M214 18l1.5-1.5m-4-5h2m14 0h2"></path></g></g></svg>
        <div class="form-check form-switch fs-6">
            <input class="form-check-input  me-0" type="checkbox" id="toggle-dark" >
            <label class="form-check-label" ></label>
        </div>
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--mdi" width="20" height="20" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="m17.75 4.09l-2.53 1.94l.91 3.06l-2.63-1.81l-2.63 1.81l.91-3.06l-2.53-1.94L12.44 4l1.06-3l1.06 3l3.19.09m3.5 6.91l-1.64 1.25l.59 1.98l-1.7-1.17l-1.7 1.17l.59-1.98L15.75 11l2.06-.05L18.5 9l.69 1.95l2.06.05m-2.28 4.95c.83-.08 1.72 1.1 1.19 1.85c-.32.45-.66.87-1.08 1.27C15.17 23 8.84 23 4.94 19.07c-3.91-3.9-3.91-10.24 0-14.14c.4-.4.82-.76 1.27-1.08c.75-.53 1.93.36 1.85 1.19c-.27 2.86.69 5.83 2.89 8.02a9.96 9.96 0 0 0 8.02 2.89m-1.64 2.02a12.08 12.08 0 0 1-7.8-3.47c-2.17-2.19-3.33-5-3.49-7.82c-2.81 3.14-2.7 7.96.31 10.98c3.02 3.01 7.84 3.12 10.98.31Z"></path></svg>
    </div>
    <div class="sidebar-toggler  x">
        <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
    </div>
</div>

resources/views/backoffice/layouts/sidebar-menu.blade.php
<ul class="menu">
    <li class="sidebar-title">Menu</li>

    <li
        class="sidebar-item active ">
        <a href="{{ route('products.index') }}" class='sidebar-link {{ Route::has('products.*') ? 'active' : '' }}'>
            <i class="bi bi-grid-fill"></i>
            <span>Products</span>
        </a>
    </li>
</ul>